### ISSUE TITLE
I ques this can work on newest Laravel version too.

### ISSUE THREAD

**Issue by from2day** [aamant/email-confirmation#2]
Hi,

at the moment this package requires "illuminate/support": "4.1.*". 
I think it can work on newest Laravel version too.

**Comment by aamant** [comment]
Hi,

I do not have time to test it right now. Did you test it?

**Comment by from2day** [comment]
Excuse me I was not quite clear. What I meant was "newer" Laravel version 4.2.17.
I have just tested it and it works fine.

Thanks for saving my time with this great, light package.

**Comment by aamant** [comment]
you can make a pull request? 
I will validate

**Comment by from2day** [comment]
Will you update to the composer package repositories? So that it would see the update version. 
At the moment it shows the old one 1.0.4 https://packagist.org/packages/aamant/email-confirmation

**Comment by aamant** [comment]
ok it's done
